### ISSUE TITLE
SubscriptionRequiredException Error

### ISSUE THREAD

**Issue by techopsveeva** [Snapchat/aws-support-tickets-aggregator#5]
Hi,

All of our AWS accounts are having Enterprise support plan, and I run into below error. Do you know what it is?

'EndpointConnectionError' object has no attribute 'response': AttributeError Traceback (most recent call last): File "/var/task/support_cases_aggregator.py", line 163, in lambda_handler return get_all_existing_cases(recent_cases_only=True) File "/var/task/support_cases_aggregator.py", line 86, in get_all_existing_cases update_recent_cases(support_cases_table, account_id, client) File
'EndpointConnectionError' object has no attribute 'response': AttributeError
Traceback (most recent call last):
  File "/var/task/support_cases_aggregator.py", line 163, in lambda_handler
    return get_all_existing_cases(recent_cases_only=True)
  File "/var/task/support_cases_aggregator.py", line 86, in get_all_existing_cases
    update_recent_cases(support_cases_table, account_id, client)
  File "/var/task/support_cases_aggregator.py", line 102, in update_recent_cases
    update_cases_helper(support_cases_table, account_id, client, kwargs)
  File "/var/task/support_cases_aggregator.py", line 125, in update_cases_helper
    if e.response["Error"]["Code"] == "SubscriptionRequiredException":
AttributeError: 'EndpointConnectionError' object has no attribute 'response'

**Comment by techopsveeva** [comment]
After doing more debug, I found out that I provisioned in the wrong region which was us-west-2. Since I deleted everything and created in us-east-1 region, the Lamda function is working without any errors.
